// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Company struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Location  string `json:"location"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type Job struct {
	ID     string `json:"id"`
	Cid    string `json:"cid"`
	Role   string `json:"role"`
	Salary string `json:"salary"`
}

type Login struct {
	Name  string `json:"name"`
	Email string `json:"email"`
	Token string `json:"Token"`
}

type LoginUser struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type NewCompnay struct {
	Name     string `json:"name"`
	Location string `json:"location"`
}

type NewJob struct {
	Cid    string `json:"cid"`
	Role   string `json:"role"`
	Salary string `json:"salary"`
}

type NewUser struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type User struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Email     string `json:"email"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}
